version: '2.3'
services:

  openldap:
    hostname: openldap
    image: osixia/openldap
    ports:
       - "389" # insecure port - use if LDAP_TLS=false
    volumes:
      #- ./ldap/users.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
      - /share/CACHEDEV5_DATA/rstudio/kerb/users.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
    environment:
      - LDAP_TLS=false
    command: ["--copy-service", "--loglevel", "debug"]

  ldapadmin:
    hostname: ldapadmin
    image: osixia/phpldapadmin
    ports:
      - "80" # insecure port - use for HTTP
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    links:
      - openldap

  selfserve:
    hostname: selfserve
    image: dtwardow/ldap-self-service-password
    ports:
      - "80"
    links:
      - openldap
    environment:
      - SERVER_HOSTNAME=selfserve
      - LSSP_ATTR_LOGIN=uid
      - LSSP_ATTR_FN=cn
      - LSSP_ATTR_MAIL=mail
      - LSSP_DEFAULT_ACTION=change
      - LDAP_BASE=dc=example,dc=org
      - LDAP_HOST=openldap
      - LDAP_PORT=389
      - LDAP_USER=cn=admin,dc=example,dc=org
      - LDAP_PASS=admin
      - SMTP_HOST=
      - SMTP_PORT=
      - SMTP_USER=
      - SMTP_PASS=
      - SMTP_FROM=
      - SMTP_TLS=off

  rstudio-workbench:
    image: rstudio-workbench-kerb:dev-bionic-2022.12.0-354.pro1 
    build: 
      context: workbench
      dockerfile: Dockerfile
      args: 
        RSTUDIO_VERSION: dev-bionic-2022.12.0-354.pro1 
    privileged: true
    ports:
      - "8790:8787"
    environment:
      RSW_LICENSE: ${RSW_LICENSE}
#    volumes:
#     - ./workbench/krb5.conf:/etc/krb5.conf
#     - ./workbench/kerb-postgres-odbc.ini:/etc/odbc.ini
    depends_on:
      - openldap
